### ISSUE TITLE
fileExists with no BucketId does not work

### ISSUE THREAD

**Issue by bittylicious** [obregonco/backblaze-b2#10]
When calling fileExists, if we don't pass in the BucketId in the options array, we should probably try to resolve this like what's done in the upload function, i.e. with the following code:

```
        if (!isset($options['BucketId']) && isset($options['BucketName'])) {
            $options['BucketId'] = $this->getBucketIdFromName($options['BucketName']);
        }
```

At present, if BucketId isn't passed in, we get an undefined index error when we try to access this in the $response line in listFiles.

At the same time, I recommend making getBucketIdFromName (and the inverse) public functions as they can be useful for callers.

**Comment by robregonm** [comment]
@bittylicious Good suggestion, could you please submit a Pull Request?

**Comment by robregonm** [comment]
Added to the latest version
