### ISSUE TITLE
Deprecated: Return type of obregonco\B2\File::jsonSerialize() is not compatible

### ISSUE THREAD

**Issue by CMeierSoftware** [obregonco/backblaze-b2#17]
### Error Message
`Deprecated: Return type of obregonco\B2\File::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/obregonco/backblaze-b2/src/File.php on line 112`

### Environment 
- `obregonco/backblaze-b2`: 1.1.0 
- PHP 8.1
- strict mode `declare(strict_types=1);`

### Bucket Settings
- private
- encrypted
- Object lock disabled

### Code to reproduce
```
<?php
declare(strict_types=1);

require_once __DIR__ . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$keyId = ''; // Fill with your details
$applicationKey = ''; // Fill with your details
$bucketName = ''; // Fill with your details


$accountId = substr($keyId, 3, 12);

$b = new obregonco\B2\Client($accountId, ['keyId' => $keyId, 'applicationKey' => $applicationKey]);
$b->version = 2;
$bucketId = $b->getBucketIdFromName($bucketName);

$options = [
	'BucketName' => $bucketName,
	'BucketId' => $bucketId,
];

$fileList = $b->listFiles($options);
var_dump($fileList);
```

### Solution
See Pull request (Update File.php) #16

**Comment by robregonm** [comment]
Merged #16 , thank you very much
