### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by wouterbles** [obregonco/backblaze-b2#2]
Thanks for your work!

I tried migrating from https://github.com/gliterd/backblaze-b2 to your package, however since the latest two commits haven't been tagged as a relase yet I received the ArrayHelper errors. This could easily fixed by tagging the latest two commits as a relase so a composer install works!

**Comment by rodolfoberrios** [comment]
I second this.

**Comment by wouterbles** [comment]
I don't really want to fork this repo, as I would like to keep most updates to this SDK in one repo. There are already a few different SDKs/forks. 

@robregonm What is your plan with this repo?

**Comment by wouterbles** [comment]
I forked and tagged a new release in https://github.com/esac-ic/backblaze-b2

**Comment by robregonm** [comment]
Hey guys,
Sorry for the delay in this fix.
Using dev-master usually solves this issue. Anyhow, I made a new render for those who don't use it.
