### ISSUE TITLE
Missing dependency - yii framework

### ISSUE THREAD

**Issue by rastographics** [obregonco/backblaze-b2#4]
Client.php has this line at the top:

`user yii\helpers\ArrayHelper;`

yii is not required by composer.json. Is it assumed we need to have the yii framework already in our project to use this backblaze library? The only reason it is included is for this one command:

```
  $options = ArrayHelper::merge([
            'headers' => $headers,
        ], $options);
```

Is it possible to rewrite this line of code without using yii? I can't run the project unless I install the yii framework

**Comment by robregonm** [comment]
Latest version already fixed that issue.
Please, make sure that you are using latest version

**Comment by rastographics** [comment]
I installed again fresh with the instructions on readme: 
`composer require obregonco/backblaze-b2`

But it is not giving me latest version. Does new release need to be made?

**Comment by robregonm** [comment]
You're right, I created a new release, so, now you can update from composer and you'll get the latest version.
