### ISSUE TITLE
Adding Prefix Support

### ISSUE THREAD

**Issue by GravisTechRyan** [obregonco/backblaze-b2#7]
I ran into a situation using your lib where i needed to search for files matching a specific criteria. I saw b2 supports a prefix option.  I added prefix into the client class and it worked without a hitch.  I'm sure there is probably a better way of doing this but here is what I changed.  I only did this for list files in order to get the id's then download the matching ones:

`
 public function listFiles(array $options)
    {
        // if FileName is set, we only attempt to retrieve information about that single file.
        $fileName = !empty($options['FileName']) ? $options['FileName'] : null;

        $prefix = !empty($options['Prefix']) ? $options['Prefix'] : null;
`

and

`        // B2 returns, at most, 1000 files per "page". Loop through the pages and compile an array of File objects.
        while (true) {
            $response = $this->request('POST', '/b2_list_file_names', [
                'json' => [
                    'bucketId' => $options['BucketId'],
                    'startFileName' => $nextFileName,
                    'maxFileCount' => $maxFileCount,
                    'prefix' => $prefix,
                ],
            ]);`

Then when i called the client i just used. (with dates in my case) for the directory structure

`$fileList = $client->listFiles([
	'BucketId' => 'somebuckid',
	'Prefix' =>  $somevariable. '/'. date("Y") . '/' . date("n") . '/' .  date("j"),
]);`

Issue:  Needs support for prefix.

**Comment by robregonm** [comment]
@GravisTechRyan Could you please submit a PR?

**Comment by robregonm** [comment]
Implemented in the latest master branch version (it'll be tagged as version 2.0)
