### ISSUE TITLE
Support for Laravel 8.x and Guzzle 7

### ISSUE THREAD

**Issue by NickStallman** [obregonco/backblaze-b2#8]
Backblaze-b2 has a requirement for guzzlehttp/guzzle: ^6.5 which means it will complain when used with Laravel 8 which requires guzzle 7.0

I'm guessing the library will probably still work just fine with Guzzle 7, the main difference being raising the mimimum PHP version.

Can the dependency be updated to support Guzzle 7?

**Comment by robregonm** [comment]
I think that it's possible, let me check the dependencies and I will update.
Also you can submit a Pull Request
